version: "3.8"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=proffy
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
  web:
    build: .
    command: yarn dev
    volumes:
      - .:/code
    ports:
      - "3000:3000"
    depends_on:
      - db